### ISSUE TITLE
Running with jetty container

### ISSUE THREAD

**Issue by tesshucom** [tesshucom/airsonic#5]
I recognize that this correspondence is for developers.
 - [[DEV Only] Jetty Embedded Support](https://github.com/airsonic/airsonic/issues/317)

There is almost no difference between tomcat and jetty in normal use.
For example, jetty operates faster in processing overcrowded requests that programmably recursively expand directory.

Since several problems occurred in a complex manner, we will make corrections for each point.

There are three perspectives, which need to be resolved in order.

1. Resolving dependencies that are barriers
2. StreamController initialization other than Tomcat
3. Avoid Spring overlapping load

**Comment by tesshucom** [comment]
### Resolving dependencies that are barriers

The dependency of assertj-core is specified and it is a barrier at compile time in jetty profile.
(Since it is unnecessary at the time of deployment, it is subject to dependency checking)

The description about assertj-core conflicts with dependency of spring-test and can not be deleted, but can be avoided by setting scope as test.

**Comment by tesshucom** [comment]
### StreamController initialization other than Tomcat

It is a problem when starting jetty.

Currently there is a flow of Connection reset in StreamController.
This is described by importing org.apache.catalina.connector.ClientAbortException.
When using jetty's profile, this catalina class does not exist, so an error occurred and the server can not be started.

Although it may not be the best method, it can be rewritten so that it is resolved by naming and does not depend on the catalina class.

Although it is not Airsonic, I have seen a similar phenomenon in a server where glassfish & tomcat is a necessary requirement before.

It may be a tips when dealing with other servers on a tomcat basis.

I have not tried Airsonic yet with Eclipse GlassFish.

**Comment by tesshucom** [comment]
### Avoid Spring overlapping load

It is not standalone, it is a problem when constructing a jetty server and deploying Airsonic war.

The fix assumed to have affected is 355868b.
Cause is a startup exception "IllegalStateException: Duplicate fragment name: spring_web" on jetty.
It suggests that different versions of Spring are loaded in duplicate.

In jetty war deployment there are two Spring reference paths.
spring-boot-dependencies and spring-boot-maven-plugin.
A simple solution is to match these referenced Spring versions.

This will allow war deployment to both Tomcat and Jetty servers.

**Comment by ghost** [comment]
Can his be reopened.  Tomcat runs much less smoothly on ARM boards - jetty runs fine.  Is there anyway to have a jetty version of Airsonic?
